# Form implementation generated from reading ui file 'qt_ui\director_main.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 300))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_statistics = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_statistics.setFont(font)
        self.pushButton_statistics.setStyleSheet("background-color: rgb(56, 84, 199);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_statistics.setObjectName("pushButton_statistics")
        self.verticalLayout.addWidget(self.pushButton_statistics)
        self.pushButton_financial = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_financial.setFont(font)
        self.pushButton_financial.setStyleSheet("background-color: rgb(56, 84, 199);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_financial.setObjectName("pushButton_financial")
        self.verticalLayout.addWidget(self.pushButton_financial)
        self.pushButton_price = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_price.setFont(font)
        self.pushButton_price.setStyleSheet("background-color: rgb(56, 84, 199);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_price.setObjectName("pushButton_price")
        self.verticalLayout.addWidget(self.pushButton_price)
        self.pushButton_hiring = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_hiring.setFont(font)
        self.pushButton_hiring.setStyleSheet("background-color: rgb(56, 84, 199);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_hiring.setObjectName("pushButton_hiring")
        self.verticalLayout.addWidget(self.pushButton_hiring)
        self.pushButton_purchase = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_purchase.setFont(font)
        self.pushButton_purchase.setStyleSheet("background-color: rgb(56, 84, 199);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_purchase.setObjectName("pushButton_purchase")
        self.verticalLayout.addWidget(self.pushButton_purchase)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow "))
        self.pushButton_statistics.setText(_translate("MainWindow", "Общая статистика клуба"))
        self.pushButton_financial.setText(_translate("MainWindow", "Финансовые показатели"))
        self.pushButton_price.setText(_translate("MainWindow", "Ценовая политика"))
        self.pushButton_hiring.setText(_translate("MainWindow", "Найм персонала"))
        self.pushButton_purchase.setText(_translate("MainWindow", "Закупки оборудования"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
