from __future__ import annotations

DARK_UI_STYLESHEET = (
    "QDialog, QMessageBox {"
    "  background-color: #111111;"
    "  color: #FFFFFF;"
    "}"
    "QMessageBox QLabel, QDialog QLabel {"
    "  color: #FFFFFF;"
    "}"
    "QPushButton {"
    "  background-color: #3854C7;"
    "  color: #FFFFFF;"
    "  border: 1px solid #2A3F9A;"
    "  padding: 6px 10px;"
    "  border-radius: 4px;"
    "}"
    "QPushButton:hover {"
    "  background-color: #4663D9;"
    "}"
    "QPushButton:pressed {"
    "  background-color: #2A3F9A;"
    "}"
    "QLineEdit, QTextEdit, QPlainTextEdit, QSpinBox, QDoubleSpinBox, QDateEdit, QComboBox {"
    "  background-color: #1A1A1A;"
    "  color: #FFFFFF;"
    "  border: 1px solid #333333;"
    "  selection-background-color: #3854C7;"
    "  selection-color: #FFFFFF;"
    "}"
    "QComboBox QAbstractItemView {"
    "  background-color: #111111;"
    "  color: #FFFFFF;"
    "  selection-background-color: #3854C7;"
    "  selection-color: #FFFFFF;"
    "}"
)
