from __future__ import annotations

DARK_UI_STYLESHEET = (
    "QDialog, QMessageBox {"
    "  background-color: #111111;"
    "  color: #FFFFFF;"
    "}"
    "QMessageBox QLabel, QDialog QLabel {"
    "  color: #FFFFFF;"
    "}"
    "QPushButton {"
    "  background-color: #3854C7;"
    "  color: #FFFFFF;"
    "  border: 1px solid #2A3F9A;"
    "  padding: 6px 10px;"
    "  border-radius: 4px;"
    "}"
    "QPushButton:hover {"
    "  background-color: #4663D9;"
    "}"
    "QPushButton:pressed {"
    "  background-color: #2A3F9A;"
    "}"
    "QLineEdit, QTextEdit, QPlainTextEdit, QSpinBox, QDoubleSpinBox, QDateEdit, QComboBox {"
    "  background-color: #1A1A1A;"
    "  color: #FFFFFF;"
    "  border: 1px solid #333333;"
    "  selection-background-color: #3854C7;"
    "  selection-color: #FFFFFF;"
    "}"
    "QComboBox QAbstractItemView {"
    "  background-color: #111111;"
    "  color: #FFFFFF;"
    "  selection-background-color: #3854C7;"
    "  selection-color: #FFFFFF;"
    "}"
)


DIRECTOR_UI_STYLESHEET = (
    "QDialog, QMessageBox {"
    "  background-color: #1A1A1A;"
    "  color: #FFFFFF;"
    "}"
    "QMainWindow {"
    "  background-color: #1A1A1A;"
    "}"
    "QWidget#centralwidget {"
    "  background-color: #1A1A1A;"
    "  border-radius: 12px;"
    "}"
    "QWidget {"
    "  font-family: 'Segoe UI';"
    "  font-size: 15px;"
    "  color: #FFFFFF;"
    "}"
    "QLabel {"
    "  color: #FFFFFF;"
    "  font-size: 15px;"
    "}"
    "QLineEdit, QTextEdit, QPlainTextEdit, QSpinBox, QDoubleSpinBox, QDateEdit, QComboBox {"
    "  background-color: #333333;"
    "  color: #FFFFFF;"
    "  border: 1px solid #555555;"
    "  border-radius: 8px;"
    "  padding: 8px;"
    "  selection-background-color: #3854C7;"
    "  selection-color: #FFFFFF;"
    "}"
    "QComboBox QAbstractItemView {"
    "  color: #FFFFFF;"
    "  background-color: #1E1E1E;"
    "  selection-background-color: #3854C7;"
    "  selection-color: #FFFFFF;"
    "}"
    "QCalendarWidget {"
    "  background-color: #1E1E1E;"
    "  color: #FFFFFF;"
    "  border: 1px solid #333333;"
    "  border-radius: 10px;"
    "}"
    "QCalendarWidget QWidget {"
    "  alternate-background-color: #252525;"
    "}"
    "QCalendarWidget QAbstractItemView {"
    "  background-color: #1E1E1E;"
    "  color: #FFFFFF;"
    "  selection-background-color: #3854C7;"
    "  selection-color: #FFFFFF;"
    "}"
    "QCalendarWidget QToolButton {"
    "  color: #FFFFFF;"
    "  background-color: transparent;"
    "  border: none;"
    "  font-weight: 600;"
    "  padding: 4px 8px;"
    "  border-radius: 8px;"
    "}"
    "QCalendarWidget QToolButton:hover {"
    "  background-color: #2A2A2A;"
    "}"
    "QCalendarWidget QMenu {"
    "  background-color: #1E1E1E;"
    "  color: #FFFFFF;"
    "  border: 1px solid #333333;"
    "}"
    "QCalendarWidget QMenu::item {"
    "  background-color: transparent;"
    "  color: #FFFFFF;"
    "  padding: 6px 12px;"
    "}"
    "QCalendarWidget QMenu::item:selected {"
    "  background-color: #3854C7;"
    "  color: #FFFFFF;"
    "}"
    "QPushButton {"
    "  background-color: #3855C7;"
    "  color: #FFFFFF;"
    "  font-size: 15px;"
    "  font-weight: 600;"
    "  border: none;"
    "  border-radius: 10px;"
    "  padding: 10px 18px;"
    "  min-height: 34px;"
    "}"
    "QPushButton:hover {"
    "  background-color: #2563EB;"
    "}"
    "QPushButton:pressed {"
    "  background-color: #1D4ED8;"
    "}"
    "QTableWidget {"
    "  background-color: #111111;"
    "  color: #FFFFFF;"
    "  gridline-color: #444444;"
    "  border: 1px solid #333333;"
    "  border-radius: 8px;"
    "}"
    "QTableWidget::item {"
    "  background-color: transparent;"
    "  padding: 4px;"
    "}"
    "QHeaderView::section {"
    "  background-color: #222222;"
    "  color: #FFFFFF;"
    "  padding: 6px;"
    "  border: 1px solid #333333;"
    "}"
    "QTableCornerButton::section {"
    "  background-color: #222222;"
    "  border: 1px solid #333333;"
    "}"
    "QTableWidget::item:alternate {"
    "  background-color: #1A1A1A;"
    "}"
    "QTableWidget::item:selected, QTableWidget::item:alternate:selected {"
    "  background-color: #3854C7;"
    "  color: #FFFFFF;"
    "}"
)


TRAINER_UI_STYLESHEET = (
    "QDialog, QMessageBox {"
    "  background-color: #1A1A1A;"
    "  color: #FFFFFF;"
    "}"
    "QMainWindow {"
    "  background-color: #1A1A1A;"
    "}"
    "QWidget#centralwidget {"
    "  background-color: #1A1A1A;"
    "  border-radius: 12px;"
    "}"
    "QWidget {"
    "  font-family: 'Segoe UI';"
    "  font-size: 15px;"
    "}"
    "QLabel {"
    "  color: #FFFFFF;"
    "  font-size: 15px;"
    "}"
    "QLineEdit, QTextEdit, QPlainTextEdit, QSpinBox, QDoubleSpinBox, QDateEdit, QComboBox {"
    "  background-color: #333333;"
    "  color: #FFFFFF;"
    "  border: 1px solid #555555;"
    "  border-radius: 8px;"
    "  padding: 8px;"
    "  selection-background-color: #3854C7;"
    "  selection-color: #FFFFFF;"
    "}"
    "QComboBox QAbstractItemView {"
    "  color: #FFFFFF;"
    "  background-color: #1E1E1E;"
    "  selection-background-color: #3854C7;"
    "  selection-color: #FFFFFF;"
    "}"
    "QCalendarWidget {"
    "  background-color: #1E1E1E;"
    "  color: #FFFFFF;"
    "  border: 1px solid #333333;"
    "  border-radius: 10px;"
    "}"
    "QCalendarWidget QWidget {"
    "  alternate-background-color: #252525;"
    "}"
    "QCalendarWidget QAbstractItemView {"
    "  background-color: #1E1E1E;"
    "  color: #FFFFFF;"
    "  selection-background-color: #3854C7;"
    "  selection-color: #FFFFFF;"
    "}"
    "QCalendarWidget QToolButton {"
    "  color: #FFFFFF;"
    "  background-color: transparent;"
    "  border: none;"
    "  font-weight: 600;"
    "  padding: 4px 8px;"
    "  border-radius: 8px;"
    "}"
    "QCalendarWidget QToolButton:hover {"
    "  background-color: #2A2A2A;"
    "}"
    "QCalendarWidget QMenu {"
    "  background-color: #1E1E1E;"
    "  color: #FFFFFF;"
    "  border: 1px solid #333333;"
    "}"
    "QCalendarWidget QMenu::item {"
    "  background-color: transparent;"
    "  color: #FFFFFF;"
    "  padding: 6px 12px;"
    "}"
    "QCalendarWidget QMenu::item:selected {"
    "  background-color: #3854C7;"
    "  color: #FFFFFF;"
    "}"
    "QPushButton {"
    "  background-color: #3855C7;"
    "  color: #FFFFFF;"
    "  font-size: 15px;"
    "  font-weight: 600;"
    "  border: none;"
    "  border-radius: 10px;"
    "  padding: 10px 18px;"
    "  min-height: 34px;"
    "}"
    "QPushButton:hover {"
    "  background-color: #2563EB;"
    "}"
    "QPushButton:pressed {"
    "  background-color: #1D4ED8;"
    "}"
    "QTableWidget {"
    "  background-color: #111111;"
    "  color: #FFFFFF;"
    "  gridline-color: #444444;"
    "  border-radius: 8px;"
    "}"
    "QHeaderView::section {"
    "  background-color: #222222;"
    "  color: #FFFFFF;"
    "  padding: 6px;"
    "  border: 1px solid #333333;"
    "}"
    "QTableWidget::item:alternate {"
    "  background-color: #1A1A1A;"
    "}"
    "QTableWidget::item:selected, QTableWidget::item:alternate:selected {"
    "  background-color: #3854C7;"
    "  color: #FFFFFF;"
    "}"
)
